namespace FitnessAPI.Models
{
    public enum LiftingEquipmentType
    {
        AbWheel,
        Barbell,
        Bodyweight,
        Cable,
        ChinUpBar,
        DeclineBench,
        DipBar,
        Dumbbell,
        EZBar,
        FlatBench,
        HammerGripPullupBar,
        InclineBench,
        Kettlebell,
        Machine,
        MedicineBall,
        PowerRack,
        PullupBar,
        ResistanceBand,
        SeatedBench,
        SmithMachine,
        SquatBox,
        SquatRack,
        TrapBar,
        WorkoutPartner
    }
}
