// <auto-generated />
using System;
using FitnessAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessAPI.Migrations
{
    [DbContext(typeof(FitnessApiDbContext))]
    [Migration("20180717003619_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitnessAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquipmentInternalData");

                    b.Property<int?>("MainMuscleGroupId");

                    b.Property<string>("Name");

                    b.Property<string>("VideoURL");

                    b.HasKey("Id");

                    b.HasIndex("MainMuscleGroupId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessAPI.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExerciseId");

                    b.Property<int>("MuscleGroupType");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("MuscleGroup");
                });

            modelBuilder.Entity("FitnessAPI.Models.Exercise", b =>
                {
                    b.HasOne("FitnessAPI.Models.MuscleGroup", "MainMuscleGroup")
                        .WithMany()
                        .HasForeignKey("MainMuscleGroupId");
                });

            modelBuilder.Entity("FitnessAPI.Models.MuscleGroup", b =>
                {
                    b.HasOne("FitnessAPI.Models.Exercise")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseId");
                });
#pragma warning restore 612, 618
        }
    }
}
